server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:api-gateway}
  config:
    import:
      - optional:nacos:${spring.application.name}.${NACOS_CONFIG_FILE_EXTENSION:yaml}?group=${NACOS_CONFIG_GROUP:DEFAULT_GROUP}&refreshEnabled=${NACOS_CONFIG_REFRESH_ENABLED:true}
  cloud:
    nacos:
      username: ${NACOS_USERNAME:dextea}
      password: ${NACOS_PASSWORD:dextea}
      server-addr: ${NACOS_SERVER_ADDR:${NACOS_URL:localhost:8848}}
      discovery:
        enabled: ${NACOS_DISCOVERY_ENABLED:true}
        namespace: ${NACOS_DISCOVERY_NAMESPACE:dextea}
        group: ${NACOS_DISCOVERY_GROUP:DEFAULT_GROUP}
      config:
        enabled: ${NACOS_CONFIG_ENABLED:true}
        namespace: ${NACOS_CONFIG_NAMESPACE:dextea}
        group: ${NACOS_CONFIG_GROUP:DEFAULT_GROUP}
        file-extension: ${NACOS_CONFIG_FILE_EXTENSION:yaml}
        refresh-enabled: ${NACOS_CONFIG_REFRESH_ENABLED:true}
