server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:customer-service}
  config:
    import:
      - optional:nacos:${NACOS_MYSQL_DATA_ID:mysql.yaml}?group=${NACOS_MYSQL_GROUP:${NACOS_CONFIG_GROUP:DEFAULT_GROUP}}&refreshEnabled=${NACOS_MYSQL_REFRESH:true}
      - optional:nacos:${NACOS_REDIS_DATA_ID:redis.yaml}?group=${NACOS_REDIS_GROUP:${NACOS_CONFIG_GROUP:DEFAULT_GROUP}}&refreshEnabled=${NACOS_REDIS_REFRESH:true}
      - optional:nacos:${NACOS_SATOKEN_DATA_ID:sa-token.yaml}?group=${NACOS_SATOKEN_GROUP:${NACOS_CONFIG_GROUP:DEFAULT_GROUP}}&refreshEnabled=${NACOS_SATOKEN_REFRESH:true}
  jackson:
    default-property-inclusion: non_null
  cloud:
    nacos:
      username: ${NACOS_USERNAME:dextea}
      password: ${NACOS_PASSWORD:dextea}
      server-addr: ${NACOS_SERVER_ADDR:${NACOS_URL:localhost:8848}}
      discovery:
        enabled: ${NACOS_DISCOVERY_ENABLED:true}
        namespace: ${NACOS_DISCOVERY_NAMESPACE:dextea}
        group: ${NACOS_DISCOVERY_GROUP:DEFAULT_GROUP}
      config:
        enabled: ${NACOS_CONFIG_ENABLED:true}
        namespace: ${NACOS_CONFIG_NAMESPACE:dextea}
        group: ${NACOS_CONFIG_GROUP:DEFAULT_GROUP}
        file-extension: ${NACOS_CONFIG_FILE_EXTENSION:yaml}
        refresh-enabled: ${NACOS_CONFIG_REFRESH_ENABLED:true}

  mail:
    host: smtp.example.com
    port: 465
    username: noreply@example.com
    password: your-smtp-password
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
