server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:store-service}
  config:
    import:
      - optional:nacos:${NACOS_MYSQL_DATA_ID:mysql.yaml}?group=${NACOS_MYSQL_GROUP:${NACOS_CONFIG_GROUP:DEFAULT_GROUP}}&refreshEnabled=${NACOS_MYSQL_REFRESH:true}
      - optional:nacos:${NACOS_AMAP_DATA_ID:amap.yaml}?group=${NACOS_AMAP_GROUP:${NACOS_CONFIG_GROUP:DEFAULT_GROUP}}&refreshEnabled=${NACOS_AMAP_REFRESH:true}
  jackson:
    default-property-inclusion: non_null
  cloud:
    nacos:
      username: ${NACOS_USERNAME:dextea}
      password: ${NACOS_PASSWORD:dextea}
      server-addr: ${NACOS_SERVER_ADDR:${NACOS_URL:localhost:8848}}
      discovery:
        enabled: ${NACOS_DISCOVERY_ENABLED:true}
        namespace: ${NACOS_DISCOVERY_NAMESPACE:dextea}
        group: ${NACOS_DISCOVERY_GROUP:DEFAULT_GROUP}
      config:
        enabled: ${NACOS_CONFIG_ENABLED:true}
        namespace: ${NACOS_CONFIG_NAMESPACE:dextea}
        group: ${NACOS_CONFIG_GROUP:DEFAULT_GROUP}
        file-extension: ${NACOS_CONFIG_FILE_EXTENSION:yaml}
        refresh-enabled: ${NACOS_CONFIG_REFRESH_ENABLED:true}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
